#!/bin/bash
HD=`cd "${0%/*}" 2>/dev/null; echo $PWD`
#
[ -f .prereq_done ] && exit 0
yum -y install cmake git mercurial
[ $? -ne 0 ] && exit 1
#yum -y install cmake
#[ $? -ne 0 ] && exit 1
# Official cmake is too old, compile from sources!
# (see cmake/build_cmake)
yum -y install autoconf libtool pkgconfig
[ $? -ne 0 ] && exit 1
yum -y install docbook-utils-pdf texi2html texinfo
[ $? -ne 0 ] && exit 1
yum -y install glibc-static glib2-static
[ $? -ne 0 ] && exit 1
yum -y install zlib-static libxml2-static openssl-static
[ $? -ne 0 ] && exit 1
yum -y install libpng-static libjpeg-turbo-static libtiff-devel libtiff-static
[ $? -ne 0 ] && exit 1
yum -y install lua-devel lua-static
[ $? -ne 0 ] && exit 1
yum -y install libusb1-devel libusb1-static
[ $? -ne 0 ] && exit 1
yum -y install ncurses-static gpm-static
[ $? -ne 0 ] && exit 1
if [ ! -s /usr/include/linux/media.h ]; then
  cp "$HD/media.h" /usr/include/linux
  [ $? -ne 0 ] && exit 1
fi
exit 0
