#!/bin/bash
HD=`cd "${0%/*}" 2> /dev/null; echo $PWD`
#
arch1() {
  case `uname -m` in
    i386 | i486 | i586 | i686 )
      echo i386
      ;;
    x86_64 | x64 )
      echo amd64
      ;;
    * )
      uname -m
      ;;
  esac
  return 0
}
#
[ -f .prereq_done ] && exit 0
apt-get update
[ $? -ne 0 ] && exit 1
apt-get -y install gcc make build-essential
[ $? -ne 0 ] && exit 1
apt-get -y install cmake git mercurial subversion
[ $? -ne 0 ] && exit 1
# If official cmake is too old, compile from sources!
# (see cmake/buil_cmake)
apt-get -y install autoconf libtool autoconf-archive pkg-config
[ $? -ne 0 ] && exit 1
apt-get -y install devscripts debhelper curl
[ $? -ne 0 ] && exit 1
apt-get -y install doxygen asciidoc xmlto gtk-doc
[ $? -ne 0 ] && exit 1
apt-get -y install libssl-dev libxml2-dev libfreetype6-dev
[ $? -ne 0 ] && exit 1
apt-get -y install libpixman-1-dev libxext-dev libsdl1.2-dev libsdl2-dev
[ $? -ne 0 ] && exit 1
apt-get -y install libjpeg-dev libpng-dev libtiff-dev libgif-dev
[ $? -ne 0 ] && exit 1
apt-get -y install libusb-1.0-0-dev libncurses5-dev libgpm-dev
[ $? -ne 0 ] && exit 1
apt-get -y install qt4-dev-tools
[ $? -ne 0 ] && exit 1
apt-get -y install openjdk-8-jdk ant
[ $? -ne 0 ] && exit 1
update-alternatives --set java /usr/lib/jvm/java-8-openjdk-`arch1`/jre/bin/java
[ $? -ne 0 ] && exit 1
if [ ! -s /usr/include/linux/media.h ]; then
  cp "$HD/media.h" /usr/include/linux
  [ $? -ne 0 ] && exit 1
fi
#
exit 0
