#!/bin/bash
HD=`cd "${0%/*}" 2> /dev/null; echo $PWD`
#
# CMake version to build
ver=3.13.4
#
if [ ! -s cmake-$ver.tar.gz ]; then
  wget http://www.cmake.org/files/v${ver%.*}/cmake-$ver.tar.gz
  [ $? -ne 0 ] && exit 1
fi
rm -fr cmake-$ver
[ $? -ne 0 ] && exit 1
tar -zxf cmake-$ver.tar.gz
[ $? -ne 0 ] && exit 1
cd cmake-$ver
[ $? -ne 0 ] && exit 1
patch -p0 < ../bootstrap.patch
[ $? -ne 0 ] && exit 1
./bootstrap
[ $? -ne 0 ] && exit 1
make install 2>&1 | tee make.log
[ $? -ne 0 ] && exit 1
#
exit 0
