#!/bin/bash
HD=`cd "${0%/*}" 2> /dev/null; echo $PWD`
#
os() {
  case `uname` in
    Linux )
      # CentOS, RHEL, Ubuntu, Debian, openSUSE, SLES, SciL, Amazon
      awk '{
  if (length($0) == 0) next;
  sub("Welcome to",""); # Appears in openSUSE and SLES
  if (match($0, "Red Hat Enterprise Linux")) { print "RHEL"; }
  else if (match($0, "SUSE Linux Enterprise Server")) { print "SLES"; }
  else if (match($0, "Scientific Linux")) { print "SciL"; }
  else { print $1; }
  exit 0
}' /etc/issue
      [ $? -ne 0 ] && return 1
      ;;
    Darwin )
      echo MacOS
      ;;
    * )
      uname
      ;;
  esac
  return 0
}
#
os_ver() {
  case `uname` in
    Linux )
      # CentOS, RHEL, Ubuntu, Debian, openSUSE, SLES, SciL, Amazon
      lsb_release -sd | awk '{
  if (length($0) == 0) next;
  sub("^[^0-9.]*", "");
  sub("\\(.*$", "");
  sub("[^0-9.]*$", "");
  print $0;
  exit 0
}'
      [ ${PIPESTATUS[0]} -ne 0 -o ${PIPESTATUS[1]} -ne 0 ] && return 1
      ;;
    Darwin )
      sw_vers | awk '/^ProductVersion:/ {
  sub("^[^0-9.]*", ""); sub("[^0-9.]*$", "");
  print $0;
  exit 0
}'
      [ ${PIPESTATUS[0]} -ne 0 -o ${PIPESTATUS[1]} -ne 0 ] && return 1
      ;;
    * )
      return 1
      ;;
  esac
  return 0
}
#
arch() {
  os=`os`
  case `uname -m` in
    i386 | i486 | i586 | i686 )
      echo i386
      ;;
    x86_64 | x64 )
      if [ "$os" == "Ubuntu" ] || [ "$os" == "Debian" ]; then
        echo amd64
      else
        echo x86_64
      fi
      ;;
    * )
      uname -m
      ;;
  esac
  return 0
}
#
# Main
#
name=ffmpeg
mver=4.1
ver=$mver
rev=1
arc=`arch`
pkg=${name}_$ver-${rev}_$arc
#
rm -fr $pkg
[ $? -ne 0 ] && exit 1
mkdir -p $pkg
[ $? -ne 0 ] && exit 1
cd $pkg
[ $? -ne 0 ] && exit 1
mkdir -p usr/local
[ $? -ne 0 ] && exit 1
cd usr/local
[ $? -ne 0 ] && exit 1
mkdir -p bin lib/frei0r-1 share/man/man1 share/man/man3 share/$name/examples share/doc/$name-$mver
[ $? -ne 0 ] && exit 1
#
BUILD=`realpath $HD/../build`
#
cp -p $BUILD/bin/ffmpeg bin/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/bin/ffprobe bin/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/bin/frmxtract bin/
[ $? -ne 0 ] && exit 1
#
cp -p $BUILD/lib/frei0r-1/*.so lib/frei0r-1/
[ $? -ne 0 ] && exit 1
#
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/doc/ffmpeg*.1 share/man/man1/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/doc/ffprobe*.1 share/man/man1/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/doc/lib*.3 share/man/man3/
[ $? -ne 0 ] && exit 1
#
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/doc/ffprobe.xsd share/$name/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/presets/*.ffpreset share/$name/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/doc/examples/*.c share/$name/examples/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/doc/examples/Makefile share/$name/examples/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/doc/examples/README share/$name/examples/
[ $? -ne 0 ] && exit 1
#
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/Changelog share/doc/$name-$ver/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/COPYING* share/doc/$name-$ver/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/CREDITS share/doc/$name-$ver/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/INSTALL* share/doc/$name-$ver/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/LICENSE* share/doc/$name-$ver/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/MAINTAINERS share/doc/$name-$ver/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/README* share/doc/$name-$ver/
[ $? -ne 0 ] && exit 1
cp -p $BUILD/ffmpeg-prefix/src/ffmpeg/RELEASE_NOTES share/doc/$name-$ver/
[ $? -ne 0 ] && exit 1
#
cd $HD/$pkg
[ $? -ne 0 ] && exit 1
size=`du -ks usr | cut -f 1`
[ $? -ne 0 ] && exit 1
mkdir -p DEBIAN
[ $? -ne 0 ] && exit 1
cd DEBIAN
[ $? -ne 0 ] && exit 1
cat > control << EOF
Package: $name
Version: 7:$ver-0ubuntu0.18.04.2
Section: video
Priority: optional
Architecture: $arc
Installed-Size: $size
Maintainer: Matjaz Rihtar <matjaz@eunet.si>
Homepage: https://github.com/mrihtar/sffmpeg
Description: Tool for transcoding, streaming and playing of multimedia files
 FFmpeg is the leading multimedia framework, able to decode, encode, transcode,
 mux, demux, stream, filter and play pretty much anything that humans and
 machines have created. It supports the most obscure ancient formats up to the
 cutting edge.
EOF
[ $? -ne 0 ] && exit 1
cd $HD
[ $? -ne 0 ] && exit 1
echo "Creating package..."
dpkg-deb -b $pkg
[ $? -ne 0 ] && exit 1
echo "Packaging done: $HD/$pkg.deb"
#
exit 0
